server:
  port: 88
spring:
  application:
    name: GATEWAY
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: gulimall
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu