server:
  port: 30000
spring:
#  main:
#    lazy-initialization: true
  application:
    name: THIRD-PARTY
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: gulimall
#      config:
#        namespace: gulimall
#        group: DEV
#        ext-config:
#          dataId: third-party
#        file-extension: yml
    alicloud:

      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: gulimall-jachiin